---

- name: Install required packages
  apt:
    name:
      - make
      - gcc
    state: present
    update_cache: yes
  when:
    - ansible_distribution in ['Debian', 'Ubuntu']
  tags:
    - install