---

- name: Install required packages
  apt:
    name: "{{ role_dcc_deb_packages }}"
    state: present
    update_cache: yes

  when:
    - ansible_distribution in ['Debian', 'Ubuntu']
  tags:
    - install