---

- name: Install required packages
  yum:
    name:
      - make
      - gcc
    state: present
    update_cache: yes
  when:
    - ansible_distribution in  ['RedHat', 'CentOS']
  tags:
    - install