---

- name: Install required packages
  yum:
    name: "{{ role_dcc_redhat_packages }}"
    state: present
    update_cache: yes
  when:
    - ansible_distribution in  ['RedHat', 'CentOS']
  tags:
    - install